### ISSUE TITLE
Can't view BLAST result tracks when not logged in

### ISSUE THREAD

**Issue by ihh** [GMOD/jbconnect-hook-jblast#108]
The "Error" track pops up instead ("An error was encountered when displaying this track. Diagnostic message: Error parsing GFF3.")
An example of what appears on the console is below.

If it is intended that BLAST results should not be visible to non-logged-in users, then surely they should not appear in the track selector either.
But if they do, and if such a track is selected without authorization, then there should be an informative error, e.g. "Not authorized", as opposed to "Error parsing GFF3" or "TypeError: Cannot read property 'replace' of undefined"

~~~~
RemoteBinaryFile.js:346 TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined
    at Object.unescape (http://23.21.254.0:1337/jbrowse/src/JBrowse/Util/GFF3.js:78:18)
    at Object.parse_feature (http://23.21.254.0:1337/jbrowse/src/JBrowse/Util/GFF3.js:28:21)
    at Object.addLine (http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/SeqFeature/GFF3/Parser.js:54:26)
    at http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/SeqFeature/GFF3.js:88:28
    at http://23.21.254.0:1337/jbrowse/src/JBrowse/Model/FileBlob.js:50:33
    at http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/RemoteBinaryFile.js:344:47
    at Object._assembleChunks (http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/RemoteBinaryFile.js:412:9)
    at Object.<anonymous> (http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/RemoteBinaryFile.js:337:23)
    at http://23.21.254.0:1337/jbrowse/src/dojo/_base/lang.js:385:55
    at Object.<anonymous> (http://23.21.254.0:1337/jbrowse/src/JBrowse/Store/RemoteBinaryFile.js:156:25) TypeError: Cannot read property 'replace' of undefined
    at Object.unescape (GFF3.js:78)
    at Object.parse_feature (GFF3.js:28)
    at Object.addLine (Parser.js:54)
    at GFF3.js:88
    at FileBlob.js:50
    at RemoteBinaryFile.js:344
    at Object._assembleChunks (RemoteBinaryFile.js:412)
    at Object.<anonymous> (RemoteBinaryFile.js:337)
    at lang.js:385
    at Object.<anonymous> (RemoteBinaryFile.js:156)
~~~~

**Comment by enuggetry** [comment]
Now, does not display tracks that have REST address.

**Comment by enuggetry** [comment]
https://actionnetwork.org/events/march-for-science-for-alison

**Comment by enuggetry** [comment]
Remaining case, URL track appearing with error. URL tracks that don't exist in the dataset should just not appear.
